# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e491a8231ea3b2fdf52529d6cf84e6585b141d6fe577ef412dcbc9c5eebda4fef2061fc6c33930240c16a604b6149811f09be193187e6f49c5c0b7af0c9e7edb

test:
  secret_key_base: ed068a2c1687e7d14615701cea938544c2fe4457e4f4e4c45b47db83c374b0810aca44a56dd40334e61d83d764a82621b02545dcdb68469e3f80b16b8f2dfaaf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
